#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use LegoMedia\LegoLand\DumpCommand;
use Symfony\Component\Console\Application;

$app = new Application();
$app->add(new DumpCommand());
$app->run();
